# Docker-compose file for TTN gateway
# Collectd reporting stack
# Requires docker-compose 1.9 or newer

# Version 2.1 for resin compatibility
version: '2.1'
services:
  # The gateway itself
  gateway:
    build: gateway
    image: freie-netzwerker/ttn-gateway
    privileged: true
    network_mode: host
    restart: always
    environment:
      GW_KEY: "${GW_KEY:?Gateway Key is mandatory}"
      GW_ID: "${GW_ID:?Gateway Id is mandatory}"
      GW_EUI: "${GW_EUI}"
      GW_LOGGER: "${GW_LOGGER:-false}"
      GW_SPI_SPEED: "${GW_SPI_SPEED}"
      GW_GPS: "${GW_GPS:-false}"
      GW_RESET_PIN: "${GW_RESET_PIN:-22}"
    devices:
      - "/dev/mem:/dev/mem"
    volumes:
      - var_ttn_vol:/var/ttn
  # Collectd
  collectd:
    build: collectd
    image: freie-netzwerker/ttn-collectd
    privileged: true
    network_mode: host
    restart: always
    environment:
      GW_COLLECTD_SERVER: "${GW_COLLECTD_SERVER}"
      GW_COLLECTD_INTERVAL: "${GW_COLLECTD_INTERVAL}"
      GW_BME280: "${GW_BME280:-false}"
      GW_BME280_ADDR: "${GW_BME280_ADDR}"
      GW_BME280_SMBUS: "${GW_BME280_SMBUS}"
    volumes:
      - var_ttn_vol:/var/ttn

volumes:
  var_ttn_vol:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
